apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-drill
  namespace: argocd        # object
spec:
  project: default
  source:                # read
    repoURL: https://github.com/thegostev/capa-lab.git
    targetRevision: HEAD-not-really
    path: apps/guestbook
  destination:           # deploy
    server: https://kubernetes.default.svc
    namespace: drill
  syncPolicy:
    syncOptions:
    - CreateNamespace=true