apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-all-
spec:
  arguments:
    parameters:
    - name: name
      value: Override
  workflowTemplateRef:
    name: capa-greeting